/**
 * Migration Script: v0 -> v1
 * 
 * Extracts only essential data from the v0 project:
 * - Categories (basic structure)
 * - Products (only id, categoryId, image, imageList)
 * - Assets (already copied by Fase 1 setup)
 * 
 * Everything else (descriptions, prices, variants, shipping) is set to null/placeholder
 * and will be populated later via admin panel + Gemini.
 */

import { readFileSync, writeFileSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');
// v0 project is at: ../AakApp relative to the parent of AakArtesanias (new project)
// But parent of AakArtesanias is AakArtesanias (the workspace root)
// And v0 (AakApp) is inside that same parent
const workspaceRoot = join(root, '..');  // Go up from AakArtesanias(new) to workspace
const v0Root = join(workspaceRoot, 'AakApp');

console.log('\n=== AakArtesanias v0 -> v1 Migration ===\n');
console.log(`v0 root: ${v0Root}`);
console.log(`v1 root: ${root}\n`);

// ---- Helper ----
function splitCommaList(str) {
  if (!str || str.trim() === '') return [];
  return str.split(',').map(s => s.trim()).filter(Boolean);
}

// ---- 1. Migrate Categories ----
console.log('--- Categories ---');
const v0CategoriesPath = join(v0Root, 'src', 'app', 'data', 'category.json');
if (existsSync(v0CategoriesPath)) {
  const v0Categories = JSON.parse(readFileSync(v0CategoriesPath, 'utf-8'));
  const v1Categories = v0Categories.map(cat => ({
    id: cat.id,
    name: cat.name,
    slug: cat.name.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, ''),
    productImage: cat.productImage || '',
    bgImage: cat.bgImage || '',
    models: cat.models || 0,
    variants: []  // Will be populated by admin
  }));
  
  const targetPath = join(root, 'src', 'app', 'core', 'data', 'categories.json');
  writeFileSync(targetPath, JSON.stringify(v1Categories, null, 2));
  console.log(`[migrate] Migrated ${v1Categories.length} categories`);
  console.log(`[migrate] Written to: ${targetPath.replace(root, '.')}`);
} else {
  console.log(`[migrate] WARNING: v0 categories.json not found at ${v0CategoriesPath}. Skipping.`);
}

// ---- 2. Migrate Products (basic structure only) ----
console.log('\n--- Products ---');
const v0ProductsPath = join(v0Root, 'src', 'app', 'data', 'products.json');
if (existsSync(v0ProductsPath)) {
  const v0Products = JSON.parse(readFileSync(v0ProductsPath, 'utf-8'));
  const now = new Date().toISOString();
  
  const v1Products = v0Products.map((prod, index) => ({
    id: prod.id || (index + 1),
    sku: `SKU-${String(prod.id || (index + 1)).padStart(4, '0')}`,
    categoryId: prod.categoryId || 1,
    name: null,                    // Will be suggested by Gemini
    slug: `producto-${prod.id || (index + 1)}`,  // Placeholder slug
    image: prod.image || '',
    imageList: splitCommaList(prod.imageCommaList),
    variantSelections: [],         // Will be configured by admin
    originalPrice: 0,              // Placeholder
    currentPrice: 0,               // Placeholder
    shippingComponents: [],        // Will be filled by admin
    featuredSection: null,
    featuredImage: '',
    tags: [],
    score: 0,
    ratings: 0,
    shortDescription: '',          // Will be generated by Gemini
    longDescription: '',           // Will be generated by Gemini
    marketingPhrase: '',           // Will be generated by Gemini
    status: 'pendiente',
    createdAt: now,
    updatedAt: now
  }));
  
  const targetPath = join(root, 'src', 'app', 'core', 'data', 'products.json');
  writeFileSync(targetPath, JSON.stringify(v1Products, null, 2));
  console.log(`[migrate] Migrated ${v1Products.length} products (basic structure)`);
  console.log(`[migrate] Written to: ${targetPath.replace(root, '.')}`);
  console.log('[migrate] NOTE: All descriptions, prices, variants are placeholders.');
} else {
  console.log(`[migrate] WARNING: v0 products.json not found at ${v0ProductsPath}. Skipping.`);
}

// ---- 3. Summary ----
console.log('\n--- Migration Complete ---');
console.log('Next steps for admin:');
console.log('  1. Open admin panel at /admin');
console.log('  2. Use Gemini to generate product names and descriptions');
console.log('  3. Configure prices, variants, and shipping data');
console.log('  4. Publish by running: npm run prebuild && ng build\n');
