/**
 * Prebuild Script for AakArtesanias
 * 
 * Prepares configuration files and verifies data integrity before Angular build.
 * 
 * Tasks:
 * 1. Read config/contact.config.json -> verify structure
 * 2. Read config/shipping-config.json -> verify structure
 * 3. Verify data integrity of src/app/core/data/products.json (if exists)
 * 4. Copy latest data from admin-api/data/ if newer
 */

import { readFileSync, existsSync, writeFileSync, statSync, copyFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');

function verifyJson(filePath, schema) {
  const fullPath = join(root, filePath);
  if (!existsSync(fullPath)) {
    console.warn(`[prebuild] WARNING: ${filePath} not found. Skipping.`);
    return false;
  }
  try {
    const data = JSON.parse(readFileSync(fullPath, 'utf-8'));
    console.log(`[prebuild] OK: ${filePath}`);
    return true;
  } catch (err) {
    console.error(`[prebuild] ERROR: ${filePath} is invalid JSON:`, err.message);
    process.exit(1);
  }
}

function syncAdminData() {
  const adminDataPath = join(root, 'admin-api', 'data', 'products.json');
  const appDataPath = join(root, 'src', 'app', 'core', 'data', 'products.json');
  
  if (existsSync(adminDataPath) && existsSync(appDataPath)) {
    const adminStat = statSync(adminDataPath);
    const appStat = statSync(appDataPath);
    
    if (adminStat.mtime > appStat.mtime) {
      console.log('[prebuild] Syncing products.json from admin-api/data/');
      copyFileSync(adminDataPath, appDataPath);
    }
  }
}

console.log('\n=== AakArtesanias Prebuild ===\n');

// Step 1: Verify configuration files
console.log('--- Config Files ---');
verifyJson('config/contact.config.json');
verifyJson('config/shipping-config.json');

// Step 2: Verify core data files
console.log('\n--- Core Data Files ---');
verifyJson('src/app/core/data/categories.json');
verifyJson('src/app/core/data/products.json');

// Step 3: Sync admin data if available
console.log('\n--- Admin Data Sync ---');
syncAdminData();

// Step 4: Generate contact.config.ts from JSON
console.log('\n--- Generating Config Files ---');
const contactConfig = JSON.parse(
  readFileSync(join(root, 'config', 'contact.config.json'), 'utf-8')
);
const contactTs = `// Auto-generated by prebuild.mjs - DO NOT EDIT
export const CONTACT_CONFIG = ${JSON.stringify(contactConfig, null, 2)} as const;
`;
writeFileSync(join(root, 'src', 'app', 'core', 'data', 'contact.config.ts'), contactTs);
console.log('[prebuild] Generated contact.config.ts');

console.log('\n=== Prebuild Complete ===\n');
