/**
 * Prebuild Script for AakArtesanias
 * 
 * Prepares configuration files and verifies data integrity before Angular build.
 * 
 * Tasks:
 * 1. Read config/contact.config.json -> verify structure
 * 2. Read config/shipping-config.json -> verify structure
 * 3. Verify data integrity of src/app/core/data/products.json (if exists)
 * 4. Sync products from Neon (Railway API) -> merge by SKU into products.json
 * 5. Generate contact.config.ts from JSON
 */

import { readFileSync, existsSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { syncProducts } from './sync-products.mjs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');

function verifyJson(filePath, schema) {
  const fullPath = join(root, filePath);
  if (!existsSync(fullPath)) {
    console.warn(`[prebuild] WARNING: ${filePath} not found. Skipping.`);
    return false;
  }
  try {
    const data = JSON.parse(readFileSync(fullPath, 'utf-8'));
    console.log(`[prebuild] OK: ${filePath}`);
    return true;
  } catch (err) {
    console.error(`[prebuild] ERROR: ${filePath} is invalid JSON:`, err.message);
    process.exit(1);
  }
}

console.log('\n=== AakArtesanias Prebuild ===\n');

// Step 1: Verify configuration files
console.log('--- Config Files ---');
verifyJson('config/contact.config.json');
verifyJson('config/shipping-config.json');

// Step 2: Verify core data files
console.log('\n--- Core Data Files ---');
verifyJson('src/app/core/data/categories.json');
verifyJson('src/app/core/data/products.json');

// Step 3: Sync products from Neon (never fails the build)
console.log('\n--- Neon Sync ---');
await syncProducts();

// Step 4: Generate contact.config.ts from JSON
console.log('\n--- Generating Config Files ---');
const contactConfig = JSON.parse(
  readFileSync(join(root, 'config', 'contact.config.json'), 'utf-8')
);
const contactTs = `// Auto-generated by prebuild.mjs - DO NOT EDIT
export const CONTACT_CONFIG = ${JSON.stringify(contactConfig, null, 2)} as const;
`;
writeFileSync(join(root, 'src', 'app', 'core', 'data', 'contact.config.ts'), contactTs);
console.log('[prebuild] Generated contact.config.ts');

console.log('\n=== Prebuild Complete ===\n');
